---
project: velo-action
vars:
  app: velo-action
  owner: cloud-platform
  region: europe-west4
  project_id: nube-velo-{{ environment }}

deploy_spec:
  - src_dir: terraform
    deploy_type: TerraformApplyV1
    terraform_version: 1.0.8
    var_files:
      - values.json
